# Generated by Django 6.0 on 2026-01-07 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('FACULTY', 'Faculty')], default='FACULTY', max_length=10),
        ),
    ]
